import { z } from 'zod';

// ── Master State ─────────────────────────────────────────────────

/**
 * Master AI lifecycle states
 */
export const MasterStateSchema = z.enum([
  'idle', // Master created but not yet started
  'exploring', // Autonomously exploring workspace
  'ready', // Exploration complete, ready for messages
  'processing', // Handling a user message
  'delegating', // Delegating task to another AI tool
  'error', // Encountered unrecoverable error
  'shutdown', // Shutting down
]);

export type MasterState = z.infer<typeof MasterStateSchema>;

// ── Exploration Summary ──────────────────────────────────────────

/**
 * Summary of workspace exploration results
 */
export const ExplorationSummarySchema = z.object({
  /** Timestamp when exploration started */
  startedAt: z.string().datetime(),

  /** Timestamp when exploration completed */
  completedAt: z.string().datetime().optional(),

  /** Current exploration status */
  status: z.enum(['in_progress', 'completed', 'failed']),

  /** Number of files scanned during exploration */
  filesScanned: z.number().int().nonnegative().default(0),

  /** Number of directories explored */
  directoriesExplored: z.number().int().nonnegative().default(0),

  /** Detected project type (e.g., 'node', 'python', 'business', 'mixed') */
  projectType: z.string().optional(),

  /** Detected frameworks/tools (e.g., ['react', 'typescript', 'vite']) */
  frameworks: z.array(z.string()).default([]),

  /** Key insights discovered about the workspace */
  insights: z.array(z.string()).default([]),

  /** Path to generated workspace map file */
  mapPath: z.string().optional(),

  /** Whether .openbridge/.git was initialized */
  gitInitialized: z.boolean().default(false),

  /** Error message if exploration failed */
  error: z.string().optional(),
});

export type ExplorationSummary = z.infer<typeof ExplorationSummarySchema>;

// ── Task Record ──────────────────────────────────────────────────

/**
 * Record of a single task executed by the Master AI
 */
export const TaskRecordSchema = z.object({
  /** Unique task identifier */
  id: z.string().min(1),

  /** Original user message that triggered this task */
  userMessage: z.string(),

  /** Sender identifier (phone number, user ID, etc.) */
  sender: z.string(),

  /** Task description (auto-generated or extracted) */
  description: z.string(),

  /** Task status */
  status: z.enum(['pending', 'processing', 'delegated', 'completed', 'failed']),

  /** AI tool that handled this task (usually 'master', or delegated tool name) */
  handledBy: z.string().default('master'),

  /** If delegated, which tool was it delegated to */
  delegatedTo: z.string().optional(),

  /** Task result or response */
  result: z.string().optional(),

  /** Error message if task failed */
  error: z.string().optional(),

  /** Timestamp when task was created */
  createdAt: z.string().datetime(),

  /** Timestamp when task started processing */
  startedAt: z.string().datetime().optional(),

  /** Timestamp when task completed */
  completedAt: z.string().datetime().optional(),

  /** Duration in milliseconds */
  durationMs: z.number().int().nonnegative().optional(),

  /** Additional metadata (file paths accessed, tools used, etc.) */
  metadata: z.record(z.unknown()).default({}),
});

export type TaskRecord = z.infer<typeof TaskRecordSchema>;

// ── Workspace Map ────────────────────────────────────────────────

/**
 * Structure of workspace-map.json generated by Master AI
 */
export const WorkspaceMapSchema = z.object({
  /** Path to the workspace root */
  workspacePath: z.string(),

  /** Project name (from package.json, directory name, or detected) */
  projectName: z.string(),

  /** Project type classification */
  projectType: z.string(),

  /** Detected frameworks and tools */
  frameworks: z.array(z.string()).default([]),

  /** Key directories and their purposes */
  structure: z
    .record(
      z.object({
        path: z.string(),
        purpose: z.string(),
        fileCount: z.number().int().nonnegative().optional(),
      }),
    )
    .default({}),

  /** Important files and their roles */
  keyFiles: z
    .array(
      z.object({
        path: z.string(),
        type: z.string(),
        purpose: z.string(),
      }),
    )
    .default([]),

  /** Entry points (main files, scripts, etc.) */
  entryPoints: z.array(z.string()).default([]),

  /** Build/test/dev commands detected */
  commands: z.record(z.string()).default({}).describe('Map of command name to command string'),

  /** Dependencies detected (from package.json, requirements.txt, etc.) */
  dependencies: z
    .array(
      z.object({
        name: z.string(),
        version: z.string().optional(),
        type: z.enum(['runtime', 'dev', 'peer']).optional(),
      }),
    )
    .default([]),

  /** High-level project summary */
  summary: z.string(),

  /** Timestamp when this map was generated */
  generatedAt: z.string().datetime(),

  /** Version of the map schema */
  schemaVersion: z.string().default('1.0.0'),
});

export type WorkspaceMap = z.infer<typeof WorkspaceMapSchema>;

// ── Agents Registry ──────────────────────────────────────────────

/**
 * Structure of agents.json in .openbridge/
 */
export const AgentsRegistrySchema = z.object({
  /** Master AI tool information */
  master: z
    .object({
      name: z.string(),
      path: z.string(),
      version: z.string(),
      role: z.literal('master'),
    })
    .nullable(),

  /** Other discovered AI tools available for delegation */
  specialists: z
    .array(
      z.object({
        name: z.string(),
        path: z.string(),
        version: z.string(),
        role: z.enum(['specialist', 'backup']),
        capabilities: z.array(z.string()).default([]),
      }),
    )
    .default([]),

  /** Timestamp when this registry was last updated */
  updatedAt: z.string().datetime(),
});

export type AgentsRegistry = z.infer<typeof AgentsRegistrySchema>;

// ── Exploration Log Entry ────────────────────────────────────────

/**
 * Single entry in exploration.log
 */
export const ExplorationLogEntrySchema = z.object({
  /** Timestamp of this log entry */
  timestamp: z.string().datetime(),

  /** Log level */
  level: z.enum(['info', 'warn', 'error']),

  /** Log message */
  message: z.string(),

  /** Additional structured data */
  data: z.record(z.unknown()).optional(),
});

export type ExplorationLogEntry = z.infer<typeof ExplorationLogEntrySchema>;

// ── Incremental Exploration (Phase 11) ──────────────────────────────

/**
 * Phase status for incremental exploration
 */
export const ExplorationPhaseSchema = z.enum([
  'pending', // Not started yet
  'in_progress', // Currently running
  'completed', // Successfully finished
  'failed', // Failed after retries
]);

export type ExplorationPhase = z.infer<typeof ExplorationPhaseSchema>;

/**
 * Status of a single directory dive in Pass 3
 */
export const DirectoryDiveStatusSchema = z.object({
  /** Directory path relative to workspace root */
  path: z.string(),

  /** Status of this directory dive */
  status: ExplorationPhaseSchema,

  /** Output file path (relative to .openbridge/exploration/dirs/) */
  outputFile: z.string().optional(),

  /** Number of attempts made */
  attempts: z.number().int().nonnegative().default(0),

  /** Error message if failed */
  error: z.string().optional(),
});

export type DirectoryDiveStatus = z.infer<typeof DirectoryDiveStatusSchema>;

/**
 * Main exploration state tracking file (exploration-state.json)
 * Single source of truth for resumability
 */
export const ExplorationStateSchema = z.object({
  /** Current phase being executed */
  currentPhase: z.enum([
    'structure_scan',
    'classification',
    'directory_dives',
    'assembly',
    'finalization',
  ]),

  /** Overall exploration status */
  status: z.enum(['pending', 'in_progress', 'completed', 'failed']),

  /** When exploration started */
  startedAt: z.string().datetime(),

  /** When exploration completed (if finished) */
  completedAt: z.string().datetime().optional(),

  /** Status of each phase */
  phases: z.object({
    structure_scan: ExplorationPhaseSchema,
    classification: ExplorationPhaseSchema,
    directory_dives: ExplorationPhaseSchema,
    assembly: ExplorationPhaseSchema,
    finalization: ExplorationPhaseSchema,
  }),

  /** Directory dive tracking (Pass 3) */
  directoryDives: z.array(DirectoryDiveStatusSchema).default([]),

  /** Total number of AI calls made */
  totalCalls: z.number().int().nonnegative().default(0),

  /** Total AI execution time in milliseconds */
  totalAITimeMs: z.number().int().nonnegative().default(0),

  /** Error message if exploration failed */
  error: z.string().optional(),
});

export type ExplorationState = z.infer<typeof ExplorationStateSchema>;

/**
 * Pass 1 output: Structure Scan (structure-scan.json)
 * Lists top-level files/dirs, counts files per directory, detects config files
 */
export const StructureScanSchema = z.object({
  /** Workspace path scanned */
  workspacePath: z.string(),

  /** Top-level files found */
  topLevelFiles: z.array(z.string()).default([]),

  /** Top-level directories found */
  topLevelDirs: z.array(z.string()).default([]),

  /** File count per directory */
  directoryCounts: z.record(z.number().int().nonnegative()).default({}),

  /** Detected configuration files (package.json, tsconfig.json, etc.) */
  configFiles: z.array(z.string()).default([]),

  /** Directories that were skipped (node_modules, .git, dist, etc.) */
  skippedDirs: z.array(z.string()).default([]),

  /** Total file count in workspace (excluding skipped) */
  totalFiles: z.number().int().nonnegative(),

  /** When this scan was performed */
  scannedAt: z.string().datetime(),

  /** Duration of the scan in milliseconds */
  durationMs: z.number().int().nonnegative(),
});

export type StructureScan = z.infer<typeof StructureScanSchema>;

/**
 * Pass 2 output: Classification (classification.json)
 * Detects project type, frameworks, commands, dependencies
 */
export const ClassificationSchema = z.object({
  /** Detected project type (e.g., 'node', 'python', 'business', 'mixed') */
  projectType: z.string(),

  /** Project name (from package.json, directory name, or detected) */
  projectName: z.string(),

  /** Detected frameworks and tools */
  frameworks: z.array(z.string()).default([]),

  /** Build/test/dev commands detected */
  commands: z.record(z.string()).default({}).describe('Map of command name to command string'),

  /** Dependencies detected (from package.json, requirements.txt, etc.) */
  dependencies: z
    .array(
      z.object({
        name: z.string(),
        version: z.string().optional(),
        type: z.enum(['runtime', 'dev', 'peer']).optional(),
      }),
    )
    .default([]),

  /** Key insights from classification */
  insights: z.array(z.string()).default([]),

  /** When classification was performed */
  classifiedAt: z.string().datetime(),

  /** Duration of classification in milliseconds */
  durationMs: z.number().int().nonnegative(),
});

export type Classification = z.infer<typeof ClassificationSchema>;

/**
 * Pass 3 output: Directory Dive Result (dirs/<dirname>.json)
 * Exploration of a single significant directory
 */
export const DirectoryDiveResultSchema = z.object({
  /** Directory path relative to workspace root */
  path: z.string(),

  /** Purpose of this directory */
  purpose: z.string(),

  /** Key files found in this directory */
  keyFiles: z
    .array(
      z.object({
        path: z.string(),
        type: z.string(),
        purpose: z.string(),
      }),
    )
    .default([]),

  /** Subdirectories and their purposes */
  subdirectories: z
    .array(
      z.object({
        path: z.string(),
        purpose: z.string(),
      }),
    )
    .default([]),

  /** File count in this directory (excluding subdirs) */
  fileCount: z.number().int().nonnegative(),

  /** Insights about this directory */
  insights: z.array(z.string()).default([]),

  /** When this dive was performed */
  exploredAt: z.string().datetime(),

  /** Duration of the dive in milliseconds */
  durationMs: z.number().int().nonnegative(),
});

export type DirectoryDiveResult = z.infer<typeof DirectoryDiveResultSchema>;

// ── Master Session ──────────────────────────────────────────────

/**
 * Persistent Master session info stored in .openbridge/master-session.json.
 * Used to resume the Master AI session across restarts.
 */
export const MasterSessionSchema = z.object({
  /** Session ID used with the Claude CLI --session-id / --resume flags */
  sessionId: z.string().min(1),

  /** When this session was first created */
  createdAt: z.string().datetime(),

  /** When this session was last used */
  lastUsedAt: z.string().datetime(),

  /** Number of messages processed in this session */
  messageCount: z.number().int().nonnegative().default(0),

  /** The allowed tools configured for this Master session */
  allowedTools: z.array(z.string()).default([]),

  /** Max turns configured for this Master session */
  maxTurns: z.number().int().positive().default(50),
});

export type MasterSession = z.infer<typeof MasterSessionSchema>;
