#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────
# cleanup-openbridge.sh
# Resets stale exploration data in a workspace .openbridge/ folder.
# Preserves user-customized prompts/ and skills/ directories.
#
# Usage:
#   ./scripts/cleanup-openbridge.sh [workspace-path] [--dry-run]
#   ./scripts/cleanup-openbridge.sh /path/to/workspace
#   ./scripts/cleanup-openbridge.sh /path/to/workspace --dry-run
#   ./scripts/cleanup-openbridge.sh --dry-run                      # uses $PWD
#
# Files deleted:
#   .openbridge/context/memory.md      — stale cross-session memory
#   .openbridge/workspace-map.json     — stale project understanding
#   .openbridge/analysis-marker.json   — triggers fresh exploration on next start
#
# SQLite cleanup (if openbridge.db exists and sqlite3 is available):
#   system_config rows  WHERE key LIKE 'exploration%'
#   workspace_state     all rows (analysis marker equivalent)
#   context_chunks      rows older than 7 days
#
# Files preserved:
#   .openbridge/prompts/               — user-customized prompt templates
#   .openbridge/skills/                — user-defined skills (if present)
#   .openbridge/openbridge.db          — SQLite DB (stale rows cleaned in-place)
# ─────────────────────────────────────────────────────────────────

set -uo pipefail

# ── Argument parsing ──────────────────────────────────────────────

DRY_RUN=false
WORKSPACE_PATH=""

for arg in "$@"; do
  case "$arg" in
    --dry-run)
      DRY_RUN=true
      ;;
    --help|-h)
      head -n 35 "$0" | grep "^#" | sed 's/^# \?//'
      exit 0
      ;;
    -*)
      echo "Unknown flag: $arg" >&2
      echo "Usage: $0 [workspace-path] [--dry-run]" >&2
      exit 1
      ;;
    *)
      if [[ -z "$WORKSPACE_PATH" ]]; then
        WORKSPACE_PATH="$arg"
      else
        echo "Unexpected argument: $arg" >&2
        exit 1
      fi
      ;;
  esac
done

# Default workspace to $PWD if not provided
if [[ -z "$WORKSPACE_PATH" ]]; then
  WORKSPACE_PATH="$PWD"
fi

# Resolve to absolute path
WORKSPACE_PATH="$(cd "$WORKSPACE_PATH" 2>/dev/null && pwd)" || {
  echo "Error: workspace path does not exist: $WORKSPACE_PATH" >&2
  exit 1
}

OPENBRIDGE_DIR="$WORKSPACE_PATH/.openbridge"

# ── Validation ────────────────────────────────────────────────────

if [[ ! -d "$OPENBRIDGE_DIR" ]]; then
  echo "No .openbridge/ folder found at: $WORKSPACE_PATH"
  echo "Nothing to clean."
  exit 0
fi

# ── Mode banner ───────────────────────────────────────────────────

if [[ "$DRY_RUN" == "true" ]]; then
  echo "=== DRY RUN — no files will be deleted ==="
fi

echo "Workspace: $WORKSPACE_PATH"
echo ""

# ── Delete helper ─────────────────────────────────────────────────

DELETED_COUNT=0

delete_if_exists() {
  local path="$1"
  local description="$2"
  if [[ -e "$path" ]]; then
    if [[ "$DRY_RUN" == "true" ]]; then
      echo "  [would delete] $path"
      echo "                 ($description)"
    else
      rm -f "$path"
      echo "  [deleted] $path"
      echo "            ($description)"
    fi
    (( DELETED_COUNT++ )) || true
  fi
}

# ── Stale exploration files ───────────────────────────────────────

echo "Stale exploration data:"
delete_if_exists \
  "$OPENBRIDGE_DIR/context/memory.md" \
  "stale cross-session memory — Master regenerates on next session"
delete_if_exists \
  "$OPENBRIDGE_DIR/workspace-map.json" \
  "stale project map — regenerated by fresh exploration"
delete_if_exists \
  "$OPENBRIDGE_DIR/analysis-marker.json" \
  "old analysis marker — deletion triggers fresh exploration on next start"

if [[ "$DELETED_COUNT" -eq 0 ]]; then
  echo "  (none found — already clean)"
fi

# ── SQLite database cleanup ───────────────────────────────────────

DB_PATH="$OPENBRIDGE_DIR/openbridge.db"

echo ""
echo "SQLite database cleanup:"

if [[ ! -f "$DB_PATH" ]]; then
  echo "  (no openbridge.db found — skipping)"
elif ! command -v sqlite3 &>/dev/null; then
  echo "  (sqlite3 not found — skipping; install sqlite3 to enable DB cleanup)"
else
  # Helper: count rows and optionally delete them from a table.
  # Skips silently if the table does not exist in this database.
  _db_cleanup_table() {
    local table="$1"
    local sql_count="$2"
    local sql_delete="$3"
    local description="$4"

    # Check that the table exists before querying it
    local exists
    exists=$(sqlite3 "$DB_PATH" \
      "SELECT COUNT(*) FROM sqlite_master WHERE type='table' AND name='${table}';" \
      2>/dev/null || echo "0")

    if [[ "$exists" == "0" ]]; then
      return
    fi

    local count
    count=$(sqlite3 "$DB_PATH" "$sql_count" 2>/dev/null || echo "0")

    if [[ "$DRY_RUN" == "true" ]]; then
      echo "  [would delete] ${count} row(s) from ${table} (${description})"
    else
      sqlite3 "$DB_PATH" "$sql_delete" 2>/dev/null || true
      echo "  [deleted] ${count} row(s) from ${table} (${description})"
    fi
  }

  # 1. Clear exploration state from key-value store
  _db_cleanup_table \
    "system_config" \
    "SELECT COUNT(*) FROM system_config WHERE key LIKE 'exploration%';" \
    "DELETE FROM system_config WHERE key LIKE 'exploration%';" \
    "exploration state keys"

  # 2. Clear workspace analysis marker (equivalent to analysis-marker.json)
  _db_cleanup_table \
    "workspace_state" \
    "SELECT COUNT(*) FROM workspace_state;" \
    "DELETE FROM workspace_state;" \
    "workspace analysis marker"

  # 3. Evict old exploration chunks (>7 days) from the chunk cache
  #    Table is context_chunks; created_at is stored as ISO-8601 text.
  _db_cleanup_table \
    "context_chunks" \
    "SELECT COUNT(*) FROM context_chunks WHERE datetime(created_at) < datetime('now', '-7 days');" \
    "DELETE FROM context_chunks WHERE datetime(created_at) < datetime('now', '-7 days');" \
    "stale exploration chunks (>7 days old)"
fi

# ── Preserved directories ─────────────────────────────────────────

echo ""
echo "Preserved (not deleted):"
if [[ -d "$OPENBRIDGE_DIR/prompts" ]]; then
  echo "  [kept] $OPENBRIDGE_DIR/prompts/"
  echo "         (user-customized prompt templates)"
fi
if [[ -d "$OPENBRIDGE_DIR/skills" ]]; then
  echo "  [kept] $OPENBRIDGE_DIR/skills/"
  echo "         (user-defined skills)"
fi
if [[ -f "$DB_PATH" ]]; then
  echo "  [kept] $DB_PATH"
  echo "         (SQLite memory — stale rows cleaned in-place above)"
fi

# ── Summary ───────────────────────────────────────────────────────

echo ""
if [[ "$DRY_RUN" == "true" ]]; then
  echo "Dry run complete. $DELETED_COUNT file(s) would be deleted."
  echo "Re-run without --dry-run to apply."
else
  echo "Cleanup complete. $DELETED_COUNT file(s) deleted."
  echo "OpenBridge will trigger fresh exploration on next startup."
fi
