#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────
# cleanup-openbridge.sh
# Resets stale exploration data in a workspace .openbridge/ folder.
# Preserves user-customized prompts/ and skills/ directories.
#
# Usage:
#   ./scripts/cleanup-openbridge.sh [workspace-path] [--dry-run]
#   ./scripts/cleanup-openbridge.sh /path/to/workspace
#   ./scripts/cleanup-openbridge.sh /path/to/workspace --dry-run
#   ./scripts/cleanup-openbridge.sh --dry-run                      # uses $PWD
#
# Files deleted:
#   .openbridge/context/memory.md      — stale cross-session memory
#   .openbridge/workspace-map.json     — stale project understanding
#   .openbridge/analysis-marker.json   — triggers fresh exploration on next start
#
# Files preserved:
#   .openbridge/prompts/               — user-customized prompt templates
#   .openbridge/skills/                — user-defined skills (if present)
#   .openbridge/openbridge.db          — SQLite memory (use --db-clean for DB cleanup)
# ─────────────────────────────────────────────────────────────────

set -uo pipefail

# ── Argument parsing ──────────────────────────────────────────────

DRY_RUN=false
WORKSPACE_PATH=""

for arg in "$@"; do
  case "$arg" in
    --dry-run)
      DRY_RUN=true
      ;;
    --help|-h)
      head -n 30 "$0" | grep "^#" | sed 's/^# \?//'
      exit 0
      ;;
    -*)
      echo "Unknown flag: $arg" >&2
      echo "Usage: $0 [workspace-path] [--dry-run]" >&2
      exit 1
      ;;
    *)
      if [[ -z "$WORKSPACE_PATH" ]]; then
        WORKSPACE_PATH="$arg"
      else
        echo "Unexpected argument: $arg" >&2
        exit 1
      fi
      ;;
  esac
done

# Default workspace to $PWD if not provided
if [[ -z "$WORKSPACE_PATH" ]]; then
  WORKSPACE_PATH="$PWD"
fi

# Resolve to absolute path
WORKSPACE_PATH="$(cd "$WORKSPACE_PATH" 2>/dev/null && pwd)" || {
  echo "Error: workspace path does not exist: $WORKSPACE_PATH" >&2
  exit 1
}

OPENBRIDGE_DIR="$WORKSPACE_PATH/.openbridge"

# ── Validation ────────────────────────────────────────────────────

if [[ ! -d "$OPENBRIDGE_DIR" ]]; then
  echo "No .openbridge/ folder found at: $WORKSPACE_PATH"
  echo "Nothing to clean."
  exit 0
fi

# ── Mode banner ───────────────────────────────────────────────────

if [[ "$DRY_RUN" == "true" ]]; then
  echo "=== DRY RUN — no files will be deleted ==="
fi

echo "Workspace: $WORKSPACE_PATH"
echo ""

# ── Delete helper ─────────────────────────────────────────────────

DELETED_COUNT=0

delete_if_exists() {
  local path="$1"
  local description="$2"
  if [[ -e "$path" ]]; then
    if [[ "$DRY_RUN" == "true" ]]; then
      echo "  [would delete] $path"
      echo "                 ($description)"
    else
      rm -f "$path"
      echo "  [deleted] $path"
      echo "            ($description)"
    fi
    (( DELETED_COUNT++ )) || true
  fi
}

# ── Stale exploration files ───────────────────────────────────────

echo "Stale exploration data:"
delete_if_exists \
  "$OPENBRIDGE_DIR/context/memory.md" \
  "stale cross-session memory — Master regenerates on next session"
delete_if_exists \
  "$OPENBRIDGE_DIR/workspace-map.json" \
  "stale project map — regenerated by fresh exploration"
delete_if_exists \
  "$OPENBRIDGE_DIR/analysis-marker.json" \
  "old analysis marker — deletion triggers fresh exploration on next start"

if [[ "$DELETED_COUNT" -eq 0 ]]; then
  echo "  (none found — already clean)"
fi

# ── Preserved directories ─────────────────────────────────────────

echo ""
echo "Preserved (not deleted):"
if [[ -d "$OPENBRIDGE_DIR/prompts" ]]; then
  echo "  [kept] $OPENBRIDGE_DIR/prompts/"
  echo "         (user-customized prompt templates)"
fi
if [[ -d "$OPENBRIDGE_DIR/skills" ]]; then
  echo "  [kept] $OPENBRIDGE_DIR/skills/"
  echo "         (user-defined skills)"
fi
if [[ -f "$OPENBRIDGE_DIR/openbridge.db" ]]; then
  echo "  [kept] $OPENBRIDGE_DIR/openbridge.db"
  echo "         (SQLite memory — use OB-1328 DB cleanup for stale rows)"
fi

# ── Summary ───────────────────────────────────────────────────────

echo ""
if [[ "$DRY_RUN" == "true" ]]; then
  echo "Dry run complete. $DELETED_COUNT file(s) would be deleted."
  echo "Re-run without --dry-run to apply."
else
  echo "Cleanup complete. $DELETED_COUNT file(s) deleted."
  echo "OpenBridge will trigger fresh exploration on next startup."
fi
