import { z } from 'zod/v3';

// ── Tool Actions ────────────────────────────────────────────────

/** Supported tool-use actions */
export const ToolActionSchema = z.enum(['api_call', 'list_endpoints', 'describe_endpoint']);

// ── Tool Call ───────────────────────────────────────────────────

/** Base fields shared by all tool calls */
const ToolCallBaseSchema = z.object({
  /** Unique ID for this tool call (generated by AI or caller) */
  id: z.string().min(1),
});

/** A tool call that invokes an API endpoint */
export const ApiCallSchema = ToolCallBaseSchema.extend({
  action: z.literal('api_call'),
  /** Endpoint ID from the workspace map */
  endpointId: z.string().min(1),
  /** Path parameter values */
  pathParams: z.record(z.string()).optional(),
  /** Query parameter values */
  queryParams: z.record(z.string()).optional(),
  /** Request body */
  body: z.unknown().optional(),
  /** Additional request headers */
  headers: z.record(z.string()).optional(),
});

/** A tool call to list all available API endpoints */
export const ListEndpointsCallSchema = ToolCallBaseSchema.extend({
  action: z.literal('list_endpoints'),
  /** Optional tag filter */
  tag: z.string().optional(),
});

/** A tool call to get full details about a specific endpoint */
export const DescribeEndpointCallSchema = ToolCallBaseSchema.extend({
  action: z.literal('describe_endpoint'),
  /** Endpoint ID to describe */
  endpointId: z.string().min(1),
});

/** Discriminated union of all tool call types */
export const ToolCallSchema = z.discriminatedUnion('action', [
  ApiCallSchema,
  ListEndpointsCallSchema,
  DescribeEndpointCallSchema,
]);

// ── Tool Result ─────────────────────────────────────────────────

/** Result of a successful tool execution */
export const ToolSuccessSchema = z.object({
  ok: z.literal(true),
  /** The tool call ID this result corresponds to */
  callId: z.string().min(1),
  /** The action that was executed */
  action: ToolActionSchema,
  /** The result data (API response body, endpoint list, etc.) */
  data: z.unknown(),
  /** Execution duration in ms */
  durationMs: z.number().nonnegative(),
});

/** Result of a failed tool execution */
export const ToolErrorSchema = z.object({
  ok: z.literal(false),
  /** The tool call ID this result corresponds to */
  callId: z.string().min(1),
  /** The action that was attempted */
  action: ToolActionSchema,
  /** Human-readable error message */
  error: z.string(),
  /** Error classification code */
  code: z.enum([
    'INVALID_CALL',
    'ENDPOINT_NOT_FOUND',
    'AUTH_ERROR',
    'TIMEOUT',
    'NETWORK_ERROR',
    'HTTP_ERROR',
    'PARSE_ERROR',
  ]),
  /** Whether the caller should retry */
  retryable: z.boolean(),
});

/** Union of success and error results */
export const ToolResultSchema = z.union([ToolSuccessSchema, ToolErrorSchema]);

// ── Tool Definition (for AI context) ────────────────────────────

/** A tool definition provided to the AI so it knows what tools are available */
export const ToolDefinitionSchema = z.object({
  /** Tool name (typically the endpoint ID or action name) */
  name: z.string().min(1),
  /** Human-readable description of what this tool does */
  description: z.string(),
  /** JSON Schema describing the expected input parameters */
  inputSchema: z.record(z.unknown()),
});

// ── Inferred Types ──────────────────────────────────────────────

export type ToolAction = z.infer<typeof ToolActionSchema>;
export type ApiCall = z.infer<typeof ApiCallSchema>;
export type ListEndpointsCall = z.infer<typeof ListEndpointsCallSchema>;
export type DescribeEndpointCall = z.infer<typeof DescribeEndpointCallSchema>;
export type ToolCall = z.infer<typeof ToolCallSchema>;
export type ToolSuccess = z.infer<typeof ToolSuccessSchema>;
export type ToolError = z.infer<typeof ToolErrorSchema>;
export type ToolResult = z.infer<typeof ToolResultSchema>;
export type ToolDefinition = z.infer<typeof ToolDefinitionSchema>;
